logging:
  level:
    org.springframework.web: DEBUG
    com.globalwonks: DEBUG

server:
  port: 8080
  ssl:
    enabled: false

#spring:
#  datasource:
#    url: jdbc:h2:file:~/mySpringBootApp-db
#    dbcp:
#      max-active: 10
#      max-idle: 10
#      max-wait: 10000
#      min-evictable-idle-time-millis: 1000
#      min-idle: 8
#      time-between-eviction-runs-millis: 10
#  http:
#    multipart:
#      max-file-size: 4096KB
#      max-request-size: 4096KB
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
##    show-sql: true